# Generated by Django 5.2.4 on 2025-07-25 09:27

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('government', '政府机关'), ('institution', '事业单位'), ('state_owned', '国企'), ('bank', '银行')], max_length=100)),
            ],
            options={
                'verbose_name': '职位类别',
                'verbose_name_plural': '职位类别',
            },
        ),
        migrations.CreateModel(
            name='JobIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': '招聘信息列表页',
                'verbose_name_plural': '招聘信息列表页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(verbose_name='发布日期')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('description', wagtailmarkdown.fields.MarkdownField(verbose_name='职位描述')),
                ('requirements', wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='职位要求')),
                ('benefits', wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='福利待遇')),
                ('application_process', wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='申请流程')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posts', to='jobs.jobcategory', verbose_name='职位类别')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='jobs.jobpost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='jobs.JobPostTag', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.region')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posts', to='jobs.region', verbose_name='地区'),
        ),
    ]
