# Generated by Django 4.2.23 on 2025-07-26 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code', 'name'], 'verbose_name': '地区', 'verbose_name_plural': '地区'},
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='用于唯一标识地区，如：110000', max_length=20, null=True, unique=True, verbose_name='地区代码'),
        ),
        migrations.AddField(
            model_name='region',
            name='level',
            field=models.CharField(choices=[('province', '省'), ('city', '市'), ('county', '县')], default='', max_length=10, verbose_name='层级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.region', verbose_name='上级地区'),
        ),
    ]
