# Generated by Django 4.2.23 on 2025-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('channel', models.CharField(choices=[('web', '网站'), ('wechat', '微信'), ('app', 'APP')], default='web', max_length=10, verbose_name='订阅渠道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '订阅用户',
                'verbose_name_plural': '订阅用户',
                'unique_together': {('phone', 'channel')},
            },
        ),
    ]
