# Generated by Django 5.2.4 on 2025-07-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '首页'},
        ),
    ]
