# Generated by Django 4.2.23 on 2025-07-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('home', '0003_alter_homepage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='简介')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '关于我们页面',
            },
            bases=('wagtailcore.page',),
        ),
    ]
